#!/usr/bin/env bash
# Bash script that displays the /etc/passwd file, using the while loop + IFS
FILE=/etc/passwd
IFS=:
while read -r USERNAME PASSWORD USER_ID GROUP_ID U_ID_INFO HOME_DIR CMD_SHELL
do
echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIR and rides $CMD_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $U_ID_INFO"
done < $FILE
