#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and displays items based on number
i=0
while [ $i -lt 10 ];do
if [ $i -eq 4 ]
then
  echo 'bad luck'
elif [ $i -eq 8 ]
then
  echo 'good luck'
fi
  echo 'Holberton School'
((i++))
done
