#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and diplays variable text
i=1
while [ $i -le 20 ]; do
if [ $i -eq 5 ]
then
  echo 'bad luck from China'
elif [ $i -eq 10 ]
then
  echo 'bad luck from Japan'
elif [ $i -eq 18 ]
then
  echo 'bad luck from Italy'
fi
  echo $i
((i++))
done
