#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file
FILE=holbertonschool
if test -e "$FILE"
then
  echo "$FILE file exists"
  if test -s "$FILE"
  then
    echo "holbertonschool file is not empty"
  fi
  if ! test -s "$FILE"
  then
    echo "holbertonschool file is empty"
  fi
  if test -f "$FILE"
  then
    echo "$FILE is a regular file"
  fi
else
  echo "$FILE file does not exist"
fi
