#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
cat /etc/hosts > temp.txt
sed -i 's/127.0.0.1/127.0.0.2/' temp.txt
echo "8.8.8.8 facebook.com" >> temp.txt
cat temp.txt > /etc/hosts
